"""empty message

Revision ID: 326badb41641
Revises: 
Create Date: 2019-10-25 15:15:05.932673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326badb41641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    op.drop_table('Flaskdb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Flaskdb',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Flaskdb_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Flaskdb_pkey')
    )
    op.create_table('todo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='todo_pkey')
    )
    # ### end Alembic commands ###
